#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.24
#  in conjunction with Tcl version 8.6
#    Jul 16, 2019 10:31:05 AM SAST  platform: Linux

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import ChangeUser_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = UserChange (root)
    ChangeUser_support.init(root, top)
    root.mainloop()

w = None
def create_UserChange(root, email_in, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    global email
    email = email_in
    rt = root
    w = tk.Toplevel (root)
    top = UserChange (w)
    ChangeUser_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_UserChange():
    global w
    w.destroy()
    w = None

class UserChange:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'
        font10 = "-family {DejaVu Sans} -size 13 -weight normal -slant"  \
            " roman -underline 0 -overstrike 0"
        font11 = "-family {DejaVu Sans} -size 15 -weight normal -slant"  \
            " roman -underline 0 -overstrike 0"
        font9 = "-family {DejaVu Sans} -size 20 -weight bold -slant "  \
            "roman -underline 0 -overstrike 0"

        top.geometry("484x266+756+142")
        top.title("Change user")

        self.Lbl_Change_user = tk.Label(top)
        self.Lbl_Change_user.place(relx=0.31, rely=0.075, height=36, width=192)
        self.Lbl_Change_user.configure(font=font9)
        self.Lbl_Change_user.configure(text='''Change user''')

        self.Lbl_want_change = tk.Label(top)
        self.Lbl_want_change.place(relx=0.103, rely=0.301, height=26, width=151)
        self.Lbl_want_change.configure(font=font10)
        self.Lbl_want_change.configure(text='''Want to change:''')

        self.Listbox1 = tk.Listbox(top)
        self.Listbox1.place(relx=0.558, rely=0.301, relheight=0.098
                , relwidth=0.339)
        self.Listbox1.configure(background="white")
        self.Listbox1.configure(font="TkFixedFont")
        self.Listbox1.configure(width=164)

        self.Lbl_new_item = tk.Label(top)
        self.Lbl_new_item.place(relx=0.103, rely=0.451, height=28, width=134)
        self.Lbl_new_item.configure(font=font11)
        self.Lbl_new_item.configure(text='''New change:''')

        self.Entry1 = tk.Entry(top)
        self.Entry1.place(relx=0.558, rely=0.451,height=23, relwidth=0.343)
        self.Entry1.configure(background="white")
        self.Entry1.configure(font="TkFixedFont")

        self.Lbl_reenter_change = tk.Label(top)
        self.Lbl_reenter_change.place(relx=0.103, rely=0.602, height=28
                , width=177)
        self.Lbl_reenter_change.configure(font=font11)
        self.Lbl_reenter_change.configure(text='''Re-enter change:''')

        self.Entry2 = tk.Entry(top)
        self.Entry2.place(relx=0.558, rely=0.602,height=23, relwidth=0.343)
        self.Entry2.configure(background="white")
        self.Entry2.configure(font="TkFixedFont")

        self.Btn_change = tk.Button(top)
        self.Btn_change.place(relx=0.124, rely=0.789, height=38, width=105)
        self.Btn_change.configure(font=font11)
        self.Btn_change.configure(text='''Change''')

        self.Btn_back = tk.Button(top)
        self.Btn_back.place(relx=0.64, rely=0.789, height=38, width=77)
        self.Btn_back.configure(font=font11)
        self.Btn_back.configure(text='''Back''')

if __name__ == '__main__':
    vp_start_gui()





