#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.24
#  in conjunction with Tcl version 8.6
#    Jul 16, 2019 10:31:05 AM SAST  platform: Linux

import sys
import re
import databaseCon

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

try:
    from tkinter import messagebox
except:
    # Python 2
    import tkMessageBox as messagebox

import ChangeUser_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = UserChange (root)
    ChangeUser_support.init(root, top)
    root.mainloop()

w = None
def create_user_change(root, email_in, db_in, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    global email, db
    email = email_in
    db = db_in
    rt = root
    w = tk.Toplevel (root)
    top = UserChange (w)
    ChangeUser_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_UserChange():
    global w
    w.destroy()
    w = None

class UserChange:
    #Function to go back to User Management window
    def back(self):
        msg = messagebox.askyesno("Change user", "Are you sure you want to leave?");
        if (msg):
            ChangeUser_support.create_User()

    #Function to check want needs to be chacnged
    def change(self):
        type=self.ltb_Want_Change.get(self.ltb_Want_Change.curselection())
        if(type=="Name"):
            self.change_name()
        else:
            if (type == "Surname"):
                self.change_last_name()
            else:
                if (type == "Email"):
                    self.change_email()
                else:
                    if (type == "Password"):
                        self.change_password()
                    else:
                        if(type == "Roll"):
                            self.change_roll()
                        else:
                            messagebox.showwarning("Change user", "Please select what to change.")

    #Function to change the name of an user and checking
    def change_name(self):
        name =self.txt_New_Item.get()
        reenter_name = self.txt_Reenter_Change.get()
        if(not(name==reenter_name)):
            messagebox.showwarning("Change user", "New item and re-enter item must match.")
        else:
            if(name=='' or reenter_name==''):
                messagebox.showwarning("Change user", "Please enter the item in both fields.")
            else:
                msg = messagebox.askyesno("Change user", "Are you sure you want to change this?")
                if (msg):
                    databaseCon.change_name(db,email,name)
                    messagebox.showinfo("Change user", "Successfully changed.")
        self.clear()

    #Function to change the last name of an user and checking
    def change_last_name(self):
        name =self.txt_New_Item.get()
        reenter_name = self.txt_Reenter_Change.get()
        if(not(name==reenter_name)):
            messagebox.showwarning("Change user", "New item and re-enter item must match.")
        else:
            if(name=='' or reenter_name==''):
                messagebox.showwarning("Change user", "Please enter the item in both fields.")
            else:
                msg = messagebox.askyesno("Change user", "Are you sure you want to change this?")
                if (msg):
                   databaseCon.change_last_name(db,email,name)
                   messagebox.showinfo("Change user", "Succefully changed.")
        self.clear()

    #Function to change the roll of an user and checking
    def change_roll(self):
        roll =self.txt_New_Item.get()
        reenter_roll = self.txt_Reenter_Change.get()
        if(not(roll==reenter_roll)):
            messagebox.showwarning("Change user", "New item and re-enter item must match.")
        else:
            if(roll=='' or reenter_roll==''):
                messagebox.showwarning("Change user", "Please enter the item in both fields.")
            else:
                if(not(roll=="admin" or roll=="user")):
                    messagebox.showwarning("Change user", "Roll must be either admin or user.")
                else:
                    msg = messagebox.askyesno("Change user", "Are you sure you want to change this?")
                    if (msg):
                        databaseCon.change_roll(db,email,roll)
                        messagebox.showinfo("Change user", "Successfully change.")
        self.clear()

    #Function to change the email of an user and checking
    def change_email(self):
        newEmail =self.txt_New_Item.get()
        reenter_email = self.txt_Reenter_Change.get()
        if (not (newEmail == reenter_email)):
            messagebox.showwarning("Change user", "New item and re-enter item must match.")
        else:
            if (newEmail == '' or reenter_email == ''):
                messagebox.showwarning("Change user", "Please enter the item in both fields.")
            else:
                if(self.check_email(newEmail)):
                    msg = messagebox.askyesno("Change user", "Are you sure you want to change this?");
                    if (msg):
                        databaseCon.change_email(db,email,newEmail)
                        messagebox.showinfo("Change user", "Successfully change.")
        self.clear()

    #Function to change the password of an user and checking
    def change_password(self):
        password = self.txt_New_Item.get()
        reenter_password = self.txt_Reenter_Change.get()
        if (not (password == reenter_password)):
            messagebox.showwarning("Change user", "New item and re-enter item must match.")
        else:
            if (password == '' or reenter_password == ''):
                messagebox.showwarning("Change user", "Please enter the item in both fields.")
            else:
                if (self.check_password(password)):
                    msg = messagebox.askyesno("Change user", "Are you sure you want to change this?");
                    if (msg):
                        databaseCon.change_password(db,email,password)
                        messagebox.showinfo("Change user", "Successfully change.")
        self.clear()

    #Function to check if the email is correct with regex
    def check_email(self, email):
        mail = email
        check = re.search("([a-z]|[A-Z]|[0-9])+\@([a-z]|[A-Z]|[0-9])+((\.(([A-Z]|[a-z]|[0-9])+))+)$",mail)
        if (check):
            return True
        else:
            messagebox.showwarning("Change user", "Invalid email.")
            self.clear()
            return False

    #Function to check if the password is correct with regex
    def check_password(self, psw):
        password = psw
        number = re.findall("[0-9]", password)
        if (not (number)):
            messagebox.showwarning("Change user", "Your password needs a number.")
            self.clear()
            return False
        caps = re.findall("[A-Z]", password)
        if (not (caps)):
            messagebox.showwarning("Change user", "Your password needs a uppercase character.")
            self.clear()
            return False
        lower = re.findall("[a-z]", password)
        if (not (lower)):
            messagebox.showwarning("Password", "Your password needs a lowercase character.")
            self.clear()
            return False
        symbols = re.findall("[!,@,#,$,%,^,&,*,.,?]", password)
        if (not (symbols)):
            messagebox.showwarning("Password", "Your password needs a symbol.")
            self.clear()
            return False
        return True

    #Function to clear the textboxs
    def clear(self):
        self.txt_New_Item.delete(0, 'end')
        self.txt_Reenter_Change.delete(0, 'end')

    #Function to create the window
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'
        fnt_text = "-family {DejaVu Sans} -size 15 -weight normal -slant roman -underline 0 -overstrike 0"
        fnt_Heading1 = "-family {DejaVu Sans} -size 20 -weight bold -slant roman -underline 0 -overstrike 0"

        top.geometry("484x318+756+142")
        top.title("Change user")

        self.lbl_Change_User = tk.Label(top)
        self.lbl_Change_User.place(relx=0.31, rely=0.075, height=36, width=192)
        self.lbl_Change_User.configure(font=fnt_Heading1)
        self.lbl_Change_User.configure(text='''Change user''')

        self.lbl_Want_Change = tk.Label(top)
        self.lbl_Want_Change.place(relx=0.103, rely=0.312, height=26, width=151)
        self.lbl_Want_Change.configure(font=fnt_text)
        self.lbl_Want_Change.configure(text='''Want to change:''')

        self.ltb_Want_Change = tk.Listbox(top)
        self.ltb_Want_Change.place(relx=0.558, rely=0.252, relheight=0.28, relwidth=0.339)
        self.ltb_Want_Change.configure(background="white")
        self.ltb_Want_Change.configure(font="TkFixedFont")
        self.ltb_Want_Change.configure(width=164)
        self.ltb_Want_Change.insert(1, "Name")
        self.ltb_Want_Change.insert(2, "Surname")
        self.ltb_Want_Change.insert(3, "Email")
        self.ltb_Want_Change.insert(4, "Password")
        self.ltb_Want_Change.insert(5, "Roll")

        self.lbl_New_Item = tk.Label(top)
        self.lbl_New_Item.place(relx=0.103, rely=0.551, height=28, width=134)
        self.lbl_New_Item.configure(font=fnt_text)
        self.lbl_New_Item.configure(text='''New change:''')

        self.txt_New_Item = tk.Entry(top)
        self.txt_New_Item.place(relx=0.558, rely=0.551,height=28, relwidth=0.343)
        self.txt_New_Item.configure(background="white")
        self.txt_New_Item.configure(font="TkFixedFont")

        self.lbl_Reenter_Change = tk.Label(top)
        self.lbl_Reenter_Change.place(relx=0.103, rely=0.652, height=28, width=177)
        self.lbl_Reenter_Change.configure(font=fnt_text)
        self.lbl_Reenter_Change.configure(text='''Re-enter change:''')

        self.txt_Reenter_Change = tk.Entry(top)
        self.txt_Reenter_Change.place(relx=0.558, rely=0.652,height=23, relwidth=0.343)
        self.txt_Reenter_Change.configure(background="white")
        self.txt_Reenter_Change.configure(font="TkFixedFont")

        self.btn_Change = tk.Button(top)
        self.btn_Change.place(relx=0.124, rely=0.789, height=38, width=105)
        self.btn_Change.configure(font=fnt_text)
        self.btn_Change.configure(text='''Change''')
        self.btn_Change.configure(command=lambda: self.change())

        self.btn_Back = tk.Button(top)
        self.btn_Back.place(relx=0.64, rely=0.789, height=38, width=77)
        self.btn_Back.configure(font=fnt_text)
        self.btn_Back.configure(text='''Back''')
        self.btn_Back.configure(command=lambda: self.back())

if __name__ == '__main__':
    vp_start_gui()





