#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.24
#  in conjunction with Tcl version 8.6
#    Jul 16, 2019 10:30:54 AM SAST  platform: Linux

import sys
import UserManagement

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

# Function which closes the window.
def destroy_window():
    global top_level
    top_level.destroy()
    top_level = None

#Function to go back to User Management window
def create_User():
    UserManagement.create_UserManagement_window(root)
    root.withdraw()

if __name__ == '__main__':
    import ChangeUser
    ChangeUser.vp_start_gui()




