#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.23
#  in conjunction with Tcl version 8.6
#    May 23, 2019 11:33:22 AM SAST  platform: Linux

import sys
import IPList
import Logging
import UserManagement


try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

#Fucntion to creat list window
def create_ip_list():
    IPList.create_win_IPList(root)
    root.withdraw()

#Fucntion to creat logs window
def create_logs():
    Logging.create_win_Logging(root)
    root.withdraw()

#Fucntion to creat users window
def create_users():
    UserManagement.create_UserManagement_window(root)
    root.withdraw()

if __name__ == '__main__':
    import Home
    Home.vp_start_gui()




