#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.24
#  in conjunction with Tcl version 8.6
#    Jul 15, 2019 11:24:59 AM SAST  platform: Linux

import sys
import Login
import Home
try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

def create_login():
    Login.create_win_Login(root)
    root.withdraw()

def create_main(roll):
    Home.create_win_Home(root,roll)
    root.withdraw()

if __name__ == '__main__':
    import register
    register.vp_start_gui()




