#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.24
#  in conjunction with Tcl version 8.6
#    Jul 16, 2019 10:11:48 AM SAST  platform: Linux

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

try:
    from tkinter import messagebox
except:
    # Python 2
    import tkMessageBox as messagebox

import UserManagement_support
import Home_support
import databaseCon
import os.path
import re

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = UserManagement_window (root)
    UserManagement_support.init(root, top)
    root.mainloop()

w = None
def create_UserManagement_window(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel (root)
    top = UserManagement_window (w)
    UserManagement_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_UserManagement_window():
    global w
    w.destroy()
    w = None

class UserManagement_window:

    def adduser(self, db):
        name = self.ent_name.get()
        surename = self.Ent_Lastname.get()
        email = self.Ent_email.get()
        password = self.Ent_password.get()
        reentered = self.Ent_reenter.get()
        if (name == ' '):
            messagebox.showwarning("UserManagement", "Plaese entere a name!")
        else:
            if (surename == ' '):
                messagebox.showwarning("UserManagement", "Please entere a surename!")
            else:
                if (password != reentered):
                    messagebox.showwarning("UserManagement", "Passwords must match!")
                    self.Ent_password.delete(0, 'end')
                    self.ent_reenter.delete(0, 'end')
                else:
                    if (self.checkPassword(password)):
                        if (self.checkEmail(email)):
                            msg = messagebox.askyesno("Roll", "Are " + name + " an admin?")
                            roll = "user"
                            if (msg):
                                roll = "admin"
                            answer = databaseCon.makeNewUser(db, name, surename, password, roll, email)
                            if (answer):
                                messagebox.showinfo("UserManagement", name + " succefully added")
                                self.ent_name.insert(tk.END, "")
                                self.Ent_Lastname.insert(tk.END, "")
                                self.Ent_email.insert(tk.END, "")
                                self.Ent_password.insert(tk.END, "")
                                self.Ent_reenter.insert(tk.END, "")
                            else:
                                messagebox.showwarning("UserManagement", "Email is in use")

    # check if the email is correct
    def checkEmail(self, email):
        mail = email
        check = re.search(
            "([a-z]|[A-Z]|[0-9])+\@([a-z]|[A-Z]|[0-9])+((\.(([A-Z]|[a-z]|[0-9])+))|(\.(([A-Z]|[a-z]|[0-9])+)){2})$",
            mail)
        if (check):
            return True
        else:
            messagebox.showwarning("Email", "Invalid email.")
            self.Ent_email.delete(0, 'end')
            return False

    # check if the email is correct
    def checkPassword(self, psw):
        password = psw
        number = re.findall("[0-9]", password)
        if (not (number)):
            messagebox.showwarning("Password", "Your password needs a number.")
            self.Ent_password.delete(0, 'end')
            self.ent_reenter.delete(0, 'end')
            return False
        caps = re.findall("[A-Z]", password)
        if (not (caps)):
            messagebox.showwarning("Password", "Your password needs a uppercase chatter.")
            self.Ent_password.delete(0, 'end')
            self.ent_reenter.delete(0, 'end')
            return False
        lower = re.findall("[a-z]", password)
        if (not (lower)):
            messagebox.showwarning("Password", "Your password needs a lowercase chatter.")
            self.Ent_password.delete(0, 'end')
            self.ent_reenter.delete(0, 'end')
            return False
        symbols = re.findall("[!,@,#,$,%,^,&,*,.,?]", password)
        if (not (symbols)):
            messagebox.showwarning("Password", "Your password needs a symbol.")
            self.Ent_password.delete(0, 'end')
            self.ent_reenter.delete(0, 'end')
            return False
        return True

    def removeUsers(self,db):
        email=self.Ent_remove_email.get()
        msg = messagebox.askyesno("Remove users", "Are  sure you want to remove "+email+" ?")
        if(msg):
            answer=databaseCon.remove(db,email)
            messagebox.showinfo("Users mangement",answer)
            self.Ent_remove_email.insert(tk.END, "")

    def back(self):
        destroy_UserManagement_window()
        Home_support.root.deiconify()

    def refeshed(self,db):
        line = databaseCon.printUsers(db)
        self.Txt_users.delete(1.0, tk.END)
        self.Txt_users.insert(tk.END, line)

    def change(self,db):
        email = self.Ent_change_email.get()
        check=databaseCon.getName(db,email)
        if(self.checkEmail(email) and not(check=="notFond")):
            UserManagement_support.createChangeUser(email)
        else:
            messagebox.showwarning("UserManagement", "Email is invalid")

    def __init__(self, top=None):
        db = databaseCon.connect()
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'
        font10 = "-family {DejaVu Sans} -size 13 -weight normal -slant"  \
            " roman -underline 0 -overstrike 0"
        font11 = "-family {DejaVu Sans} -size 15 -weight bold -slant "  \
            "roman -underline 0 -overstrike 0"
        font12 = "-family {DejaVu Sans} -size 13 -weight bold -slant "  \
            "roman -underline 0 -overstrike 0"
        font13 = "-family {DejaVu Sans} -size 15 -weight normal -slant"  \
            " roman -underline 0 -overstrike 0"
        font9 = "-family {DejaVu Sans} -size 20 -weight bold -slant "  \
            "roman -underline 0 -overstrike 0"

        top.geometry("862x467+756+142")
        top.title("User management")
        top.configure(highlightcolor="black")

        self.lbl_Header1 = tk.Label(top)
        self.lbl_Header1.place(relx=0.293, rely=0.043, height=36, width=351)
        self.lbl_Header1.configure(activebackground="#f9f9f9")
        self.lbl_Header1.configure(font=font9)
        self.lbl_Header1.configure(text='''User management''')

        self.btn_close = tk.Button(top)
        self.btn_close.place(relx=0.857, rely=0.878, height=38, width=82)
        self.btn_close.configure(activebackground="#f9f9f9")
        self.btn_close.configure(font=font13)
        self.btn_close.configure(text='''Close''')
        self.btn_close.configure(command=lambda: self.back())

        self.lbl_name = tk.Label(top)
        self.lbl_name.place(relx=0.059, rely=0.193, height=28, width=69)
        self.lbl_name.configure(activebackground="#f9f9f9")
        self.lbl_name.configure(font=font10)
        self.lbl_name.configure(text='''Name:''')

        self.lbl_lastName = tk.Label(top)
        self.lbl_lastName.place(relx=0.059, rely=0.257, height=27, width=106)
        self.lbl_lastName.configure(activebackground="#f9f9f9")
        self.lbl_lastName.configure(font=font10)
        self.lbl_lastName.configure(text='''Last name:''')

        self.Ent_Lastname = tk.Entry(top)
        self.Ent_Lastname.place(relx=0.305, rely=0.268, height=23
                , relwidth=0.195)
        self.Ent_Lastname.configure(background="white")
        self.Ent_Lastname.configure(font="TkFixedFont")
        self.Ent_Lastname.configure(selectbackground="#c4c4c4")

        self.ent_name = tk.Entry(top)
        self.ent_name.place(relx=0.305, rely=0.193,height=23, relwidth=0.195)
        self.ent_name.configure(background="white")
        self.ent_name.configure(font="TkFixedFont")
        self.ent_name.configure(selectbackground="#c4c4c4")

        self.Lbl_email = tk.Label(top)
        self.Lbl_email.place(relx=0.053, rely=0.321, height=28, width=67)
        self.Lbl_email.configure(activebackground="#f9f9f9")
        self.Lbl_email.configure(font=font10)
        self.Lbl_email.configure(text='''Email:''')

        self.Ent_email = tk.Entry(top)
        self.Ent_email.place(relx=0.305, rely=0.332,height=23, relwidth=0.195)
        self.Ent_email.configure(background="white")
        self.Ent_email.configure(font="TkFixedFont")
        self.Ent_email.configure(selectbackground="#c4c4c4")

        self.Lbl_password = tk.Label(top)
        self.Lbl_password.place(relx=0.053, rely=0.385, height=28, width=104)
        self.Lbl_password.configure(activebackground="#f9f9f9")
        self.Lbl_password.configure(font=font10)
        self.Lbl_password.configure(text='''Password:''')

        self.Ent_password = tk.Entry(top)
        self.Ent_password.place(relx=0.305, rely=0.407, height=23
                , relwidth=0.195)
        self.Ent_password.configure(background="white")
        self.Ent_password.configure(font="TkFixedFont")
        self.Ent_password.configure(selectbackground="#c4c4c4")
        self.Ent_password.configure(show="*")

        self.Lbl_reenter = tk.Label(top)
        self.Lbl_reenter.place(relx=0.047, rely=0.471, height=28, width=196)
        self.Lbl_reenter.configure(activebackground="#f9f9f9")
        self.Lbl_reenter.configure(font=font10)
        self.Lbl_reenter.configure(text='''Re-enter Password:''')

        self.Ent_reenter = tk.Entry(top)
        self.Ent_reenter.place(relx=0.305, rely=0.471, height=23, relwidth=0.195)

        self.Ent_reenter.configure(background="white")
        self.Ent_reenter.configure(font="TkFixedFont")
        self.Ent_reenter.configure(selectbackground="#c4c4c4")
        self.Ent_reenter.configure(show="*")

        self.lbl_add = tk.Label(top)
        self.lbl_add.place(relx=0.223, rely=0.128, height=28, width=55)
        self.lbl_add.configure(activebackground="#f9f9f9")
        self.lbl_add.configure(font=font11)
        self.lbl_add.configure(text='''Add:''')

        self.Txt_users = tk.Text(top)
        self.Txt_users.place(relx=0.54, rely=0.193, relheight=0.63
                , relwidth=0.43)
        self.Txt_users.configure(background="white")
        self.Txt_users.configure(font="TkTextFont")
        self.Txt_users.configure(selectbackground="#c4c4c4")
        self.Txt_users.configure(width=366)
        self.Txt_users.configure(wrap="word")

        self.Lbl_users = tk.Label(top)
        self.Lbl_users.place(relx=0.751, rely=0.128, height=28, width=76)
        self.Lbl_users.configure(activebackground="#f9f9f9")
        self.Lbl_users.configure(font=font11)
        self.Lbl_users.configure(text='''Users:''')

        self.lbl_remove = tk.Label(top)
        self.lbl_remove.place(relx=0.2, rely=0.557, height=28, width=103)
        self.lbl_remove.configure(activebackground="#f9f9f9")
        self.lbl_remove.configure(font=font11)
        self.lbl_remove.configure(text='''Remove:''')

        self.Lbl_remove_email = tk.Label(top)
        self.Lbl_remove_email.place(relx=0.07, rely=0.642, height=26, width=59)
        self.Lbl_remove_email.configure(activebackground="#f9f9f9")
        self.Lbl_remove_email.configure(font=font10)
        self.Lbl_remove_email.configure(text='''Email:''')

        self.Ent_remove_email = tk.Entry(top)
        self.Ent_remove_email.place(relx=0.305, rely=0.642, height=23
                , relwidth=0.195)
        self.Ent_remove_email.configure(background="white")
        self.Ent_remove_email.configure(font="TkFixedFont")
        self.Ent_remove_email.configure(selectbackground="#c4c4c4")

        self.Lbl_Change = tk.Label(top)
        self.Lbl_Change.place(relx=0.211, rely=0.707, height=26, width=84)
        self.Lbl_Change.configure(activebackground="#f9f9f9")
        self.Lbl_Change.configure(font=font12)
        self.Lbl_Change.configure(text='''Change:''')

        self.Lbl_change_email = tk.Label(top)
        self.Lbl_change_email.place(relx=0.07, rely=0.771, height=26, width=59)
        self.Lbl_change_email.configure(activebackground="#f9f9f9")
        self.Lbl_change_email.configure(font=font10)
        self.Lbl_change_email.configure(text='''Email:''')

        self.Ent_change_email = tk.Entry(top)
        self.Ent_change_email.place(relx=0.305, rely=0.771,height=23, relwidth=0.195)
        self.Ent_change_email.configure(background="white")
        self.Ent_change_email.configure(font="TkFixedFont")
        self.Ent_change_email.configure(selectbackground="#c4c4c4")

        self.Btn_add = tk.Button(top)
        self.Btn_add.place(relx=0.07, rely=0.878, height=36, width=87)
        self.Btn_add.configure(activebackground="#f9f9f9")
        self.Btn_add.configure(font=font13)
        self.Btn_add.configure(text='''Add''')
        self.Btn_add.configure(command=lambda: self.adduser(db))

        self.Btn_remove = tk.Button(top)
        self.Btn_remove.place(relx=0.211, rely=0.878, height=38, width=109)
        self.Btn_remove.configure(activebackground="#f9f9f9")
        self.Btn_remove.configure(font=font13)
        self.Btn_remove.configure(text='''Remove''')
        self.Btn_remove.configure(command=lambda: self.removeUsers(db))

        self.Btn_Change = tk.Button(top)
        self.Btn_Change.place(relx=0.387, rely=0.878, height=38, width=105)
        self.Btn_Change.configure(activebackground="#f9f9f9")
        self.Btn_Change.configure(font=font13)
        self.Btn_Change.configure(text='''Change''')
        self.Btn_Change.configure(command=lambda: self.change(db))

        self.Btn_Refesh = tk.Button(top)
        self.Btn_Refesh.place(relx=0.704, rely=0.878, height=38, width=96)
        self.Btn_Refesh.configure(activebackground="#f9f9f9")
        self.Btn_Refesh.configure(font=font13)
        self.Btn_Refesh.configure(text='''Refesh''')
        self.Btn_Refesh.configure(command=lambda: self.refeshed(db))

if __name__ == '__main__':
    vp_start_gui()





